# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FileVariable(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, longname: str=None, type: str=None):  # noqa: E501
        """FileVariable - a model defined in Swagger

        :param name: The name of this FileVariable.  # noqa: E501
        :type name: str
        :param longname: The longname of this FileVariable.  # noqa: E501
        :type longname: str
        :param type: The type of this FileVariable.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'name': str,
            'longname': str,
            'type': str
        }

        self.attribute_map = {
            'name': 'name',
            'longname': 'longname',
            'type': 'type'
        }
        self._name = name
        self._longname = longname
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'FileVariable':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileVariable of this FileVariable.  # noqa: E501
        :rtype: FileVariable
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this FileVariable.


        :return: The name of this FileVariable.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FileVariable.


        :param name: The name of this FileVariable.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def longname(self) -> str:
        """Gets the longname of this FileVariable.


        :return: The longname of this FileVariable.
        :rtype: str
        """
        return self._longname

    @longname.setter
    def longname(self, longname: str):
        """Sets the longname of this FileVariable.


        :param longname: The longname of this FileVariable.
        :type longname: str
        """
        if longname is None:
            raise ValueError("Invalid value for `longname`, must not be `None`")  # noqa: E501

        self._longname = longname

    @property
    def type(self) -> str:
        """Gets the type of this FileVariable.


        :return: The type of this FileVariable.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this FileVariable.


        :param type: The type of this FileVariable.
        :type type: str
        """
        allowed_values = ["1D", "2D", "Geo2D"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
